// src/App.jsx
import React, { useState, useEffect, useRef } from 'react';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import StatusBar from './components/StatusBar';
import TournamentInfo from './components/TournamentInfo';
import Dashboard from './components/Dashboard';
import DivisionManager from './components/DivisionManager';
import DivisionView from './components/DivisionView';
import LandingScreen from './components/LandingScreen';
import SetupWizard from './components/SetupWizard';
import PublicTournament from './pages/PublicTournament';
import { useTournamentState } from './hooks/useTournamentState.js';
import { useWizardStore } from './stores/wizardStore.js';
import { supabase } from './services/supabaseClient.js';

// Default tournament structure
const createDefaultTournament = () => ({
  name: '',
  mode: '4on4',
  startDate: '',
  endDate: '',
  divisions: [],
  activeDivisionId: null,
  // Tournament-level wiki config (set by Wiki Setup Wizard)
  wikiConfig: {
    enabled: false,
    parentPage: '', // e.g., "The Big 4"
    seasonPage: '', // e.g., "The Big 4/Season 2"
    navbox: '', // e.g., "TB4 Navbox"
    infobox: {}, // Explicit overrides: { name, image, organizers, website, discord, ... }
    pages: [], // [{name, link, type}] — generated by wizard
  },
});

// Default division structure
export const createDefaultDivision = (name = 'Division 1') => ({
  id: `div-${Date.now()}`,
  name,
  // Format settings
  format: 'groups', // groups, single-elim, double-elim
  numGroups: 2,
  teamsPerGroup: 4,
  advanceCount: 2,
  // Group stage format
  groupStageBestOf: 3,
  groupStageType: 'bestof', // 'bestof' or 'playall'
  groupMeetings: 1, // 1 = single round-robin, 2 = double, etc.
  matchPace: 'weekly', // daily, twice-weekly, weekly, biweekly, flexible
  // Playoff settings
  playoffFormat: 'single', // 'single' or 'double' elimination
  playoffTeams: 4, // 4 or 8 teams in playoffs
  playoffR32BestOf: 3,
  playoffR32Type: 'bestof',
  playoffR16BestOf: 3,
  playoffR16Type: 'bestof',
  playoffQFBestOf: 3,
  playoffQFType: 'bestof',
  playoffSFBestOf: 3,
  playoffSFType: 'bestof',
  playoffFinalBestOf: 5,
  playoffFinalType: 'bestof',
  playoff3rdBestOf: 0,
  playoff3rdType: 'bestof',
  // Double elim specific
  playoffLosersBestOf: 3,
  playoffLosersType: 'bestof',
  playoffGrandFinalBestOf: 5,
  playoffGrandFinalType: 'bestof',
  playoffBracketReset: true,
  // Points system (no draws in Quake)
  pointsWin: 3,
  pointsLoss: 0,
  // Tie-breakers (in order of priority)
  tieBreakers: ['mapDiff', 'fragDiff', 'headToHead'],
  // Data
  teams: [],
  schedule: [],
  bracket: createDefaultBracket('single', 4),
  rawMaps: [],
  // Wiki auto-publish config (per division)
  wikiConfig: {
    enabled: false,
    targets: [], // [{ type: 'standings'|'matches'|'bracket'|'full', page: '', section: '' }]
  },
});

// Helper to create bracket structure based on format and team count
export function createDefaultBracket(format, teamCount) {
  if (format === 'double') {
    return createDoubleElimBracket(teamCount);
  }
  return createSingleElimBracket(teamCount);
}

function createSingleElimBracket(teamCount) {
  const bracket = {
    format: 'single',
    teamCount,
    winners: {},
    thirdPlace: { id: '3rd', team1: '', team2: '' },
  };

  // 32 teams: R32 → R16 → QF → SF → F
  if (teamCount >= 32) {
    bracket.winners.round32 = Array.from({ length: 16 }, (_, i) => ({
      id: `w-r32-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.round16 = Array.from({ length: 8 }, (_, i) => ({
      id: `w-r16-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
  }
  // 16 teams: R16 → QF → SF → F
  else if (teamCount >= 16) {
    bracket.winners.round16 = Array.from({ length: 8 }, (_, i) => ({
      id: `w-r16-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
  }
  // 12 teams: Need 4 byes, 8 play first round → QF → SF → F
  else if (teamCount >= 12) {
    bracket.winners.round12 = Array.from({ length: 4 }, (_, i) => ({
      id: `w-r12-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
  }
  // 8 teams: QF → SF → F
  else if (teamCount >= 8) {
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
  }

  // All brackets have SF and F
  bracket.winners.semiFinals = [
    { id: 'w-sf1', team1: '', team2: '' },
    { id: 'w-sf2', team1: '', team2: '' },
  ];

  bracket.winners.final = { id: 'w-final', team1: '', team2: '' };

  return bracket;
}

function createDoubleElimBracket(teamCount) {
  const bracket = {
    format: 'double',
    teamCount,
    winners: {},
    losers: {},
    grandFinal: { id: 'grand-final', team1: '', team2: '' },
    bracketReset: { id: 'bracket-reset', team1: '', team2: '', needed: false },
  };

  // 32 teams
  if (teamCount >= 32) {
    bracket.winners.round32 = Array.from({ length: 16 }, (_, i) => ({
      id: `w-r32-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.round16 = Array.from({ length: 8 }, (_, i) => ({
      id: `w-r16-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
    // Complex losers bracket for 32 teams
    bracket.losers.round1 = Array.from({ length: 8 }, (_, i) => ({
      id: `l-r1-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round2 = Array.from({ length: 8 }, (_, i) => ({
      id: `l-r2-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round3 = Array.from({ length: 4 }, (_, i) => ({
      id: `l-r3-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round4 = Array.from({ length: 4 }, (_, i) => ({
      id: `l-r4-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round5 = Array.from({ length: 2 }, (_, i) => ({
      id: `l-r5-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round6 = [{ id: 'l-r6-1', team1: '', team2: '' }];
    bracket.losers.final = { id: 'l-final', team1: '', team2: '' };
  }
  // 16 teams
  else if (teamCount >= 16) {
    bracket.winners.round16 = Array.from({ length: 8 }, (_, i) => ({
      id: `w-r16-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round1 = Array.from({ length: 4 }, (_, i) => ({
      id: `l-r1-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round2 = Array.from({ length: 4 }, (_, i) => ({
      id: `l-r2-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round3 = Array.from({ length: 2 }, (_, i) => ({
      id: `l-r3-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round4 = [{ id: 'l-r4-1', team1: '', team2: '' }];
    bracket.losers.final = { id: 'l-final', team1: '', team2: '' };
  }
  // 12 teams
  else if (teamCount >= 12) {
    bracket.winners.round12 = Array.from({ length: 4 }, (_, i) => ({
      id: `w-r12-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.winners.quarterFinals = Array.from({ length: 4 }, (_, i) => ({
      id: `w-qf${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round1 = Array.from({ length: 2 }, (_, i) => ({
      id: `l-r1-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round2 = Array.from({ length: 2 }, (_, i) => ({
      id: `l-r2-${i + 1}`,
      team1: '',
      team2: '',
    }));
    bracket.losers.round3 = [{ id: 'l-r3-1', team1: '', team2: '' }];
    bracket.losers.final = { id: 'l-final', team1: '', team2: '' };
  }
  // 8 teams
  else if (teamCount >= 8) {
    bracket.winners.quarterFinals = [
      { id: 'w-qf1', team1: '', team2: '' },
      { id: 'w-qf2', team1: '', team2: '' },
      { id: 'w-qf3', team1: '', team2: '' },
      { id: 'w-qf4', team1: '', team2: '' },
    ];
    bracket.losers.round1 = [
      { id: 'l-r1-1', team1: '', team2: '' },
      { id: 'l-r1-2', team1: '', team2: '' },
    ];
    bracket.losers.round2 = [
      { id: 'l-r2-1', team1: '', team2: '' },
      { id: 'l-r2-2', team1: '', team2: '' },
    ];
    bracket.losers.round3 = [{ id: 'l-r3-1', team1: '', team2: '' }];
    bracket.losers.final = { id: 'l-final', team1: '', team2: '' };
  }
  // 4 teams
  else {
    bracket.losers.round1 = [{ id: 'l-r1-1', team1: '', team2: '' }];
    bracket.losers.final = { id: 'l-final', team1: '', team2: '' };
  }

  bracket.winners.semiFinals = [
    { id: 'w-sf1', team1: '', team2: '' },
    { id: 'w-sf2', team1: '', team2: '' },
  ];

  bracket.winners.final = { id: 'w-final', team1: '', team2: '' };

  return bracket;
}

function App() {
  // Public route: #/t/tournament-slug
  const [hashRoute, setHashRoute] = useState(window.location.hash);

  useEffect(() => {
    const handler = () => setHashRoute(window.location.hash);
    window.addEventListener('hashchange', handler);
    return () => window.removeEventListener('hashchange', handler);
  }, []);

  if (hashRoute.startsWith('#/t/')) {
    return <PublicTournament slug={hashRoute.replace('#/t/', '')} />;
  }

  // Main tournament state — localStorage + Supabase (Phase 2)
  const {
    tournament,
    setTournament,
    activeDivisionId,
    setActiveDivisionId,
    isLoading,
    loadFromCloud,
    cloudTournaments,
  } = useTournamentState();

  // App mode: 'landing' | 'wizard' | 'app'
  // Skip landing if localStorage already has a tournament with divisions
  const [appMode, setAppMode] = useState(() =>
    tournament.divisions?.length > 0 ? 'app' : 'landing'
  );

  const { setDraftId: setWizardDraftId } = useWizardStore();

  // UI state
  const [activeTab, setActiveTab] = useState('info'); // info, divisions, division
  const [activeSubTab, setActiveSubTab] = useState('setup'); // section tabs in header
  const [initialSubTab, setInitialSubTab] = useState(null);

  // Get active division
  const activeDivision = tournament.divisions.find((d) => d.id === activeDivisionId);

  // Update tournament info (not division-specific)
  const updateTournamentInfo = (updates) => {
    setTournament((prev) => ({ ...prev, ...updates }));
  };

  // Add a new division (raw — no tab switch, used by wizard)
  const addDivisionRaw = (name) => {
    const newDiv = createDefaultDivision(name);
    setTournament((prev) => ({
      ...prev,
      divisions: [...prev.divisions, newDiv],
    }));
    setActiveDivisionId(newDiv.id);
    return newDiv.id;
  };

  // Add a new division (with tab switch for full app mode)
  const addDivision = (name) => {
    const id = addDivisionRaw(name);
    if (appMode === 'app') {
      setActiveTab('division');
    }
    return id;
  };

  // Remove a division
  const removeDivision = (divId) => {
    setTournament((prev) => ({
      ...prev,
      divisions: prev.divisions.filter((d) => d.id !== divId),
    }));
    if (activeDivisionId === divId) {
      const remaining = tournament.divisions.filter((d) => d.id !== divId);
      setActiveDivisionId(remaining.length > 0 ? remaining[0].id : null);
      if (remaining.length === 0) {
        setActiveTab('divisions');
      }
    }
  };

  // Update a specific division
  const updateDivision = (divId, updates) => {
    setTournament((prev) => ({
      ...prev,
      divisions: prev.divisions.map((d) => (d.id === divId ? { ...d, ...updates } : d)),
    }));
  };

  // Duplicate a division (copy settings, not data)
  const duplicateDivision = (divId) => {
    const source = tournament.divisions.find((d) => d.id === divId);
    if (!source) return;

    const newDiv = {
      ...createDefaultDivision(`${source.name} (Copy)`),
      // Copy format settings
      format: source.format,
      numGroups: source.numGroups,
      teamsPerGroup: source.teamsPerGroup,
      advanceCount: source.advanceCount,
      groupStageBestOf: source.groupStageBestOf,
      playoffQFBestOf: source.playoffQFBestOf,
      playoffSFBestOf: source.playoffSFBestOf,
      playoffFinalBestOf: source.playoffFinalBestOf,
      playoff3rdBestOf: source.playoff3rdBestOf,
      pointsWin: source.pointsWin,
      pointsDraw: source.pointsDraw,
      pointsLoss: source.pointsLoss,
    };

    setTournament((prev) => ({
      ...prev,
      divisions: [...prev.divisions, newDiv],
    }));

    return newDiv.id;
  };

  // Reset entire tournament
  const resetTournament = () => {
    if (!window.confirm('Reset ALL tournament data? This cannot be undone.')) return;
    if (!window.confirm('This will delete all divisions, teams, and results. Continue?')) return;

    setTournament(createDefaultTournament());
    setActiveDivisionId(null);
    setActiveTab('info');
  };

  // Import tournament data
  const importTournament = (data) => {
    if (data.divisions) {
      setTournament(data);
      if (data.divisions.length > 0) {
        setActiveDivisionId(data.activeDivisionId || data.divisions[0].id);
        setActiveTab('division');
      }
      setAppMode('app');
    }
  };

  // Calculate stats
  const stats = {
    divisions: tournament.divisions.length,
    teams: tournament.divisions.reduce((sum, d) => sum + (d.teams?.length || 0), 0),
    matches: tournament.divisions.reduce((sum, d) => sum + (d.schedule?.length || 0), 0),
    completed: tournament.divisions.reduce(
      (sum, d) => sum + (d.schedule?.filter((m) => m.status === 'completed')?.length || 0),
      0
    ),
  };

  // Check if there's meaningful existing data
  const hasExistingData = !!(tournament.name || tournament.divisions.length > 0);

  const renderContent = () => {
    switch (activeTab) {
      case 'info':
        return (
          <Dashboard
            tournament={tournament}
            onNavigateToDivision={(divId, subTab) => {
              setActiveDivisionId(divId);
              setInitialSubTab(subTab || 'schedule');
              setActiveTab('division');
            }}
          />
        );
      case 'divisions':
        return (
          <DivisionManager
            divisions={tournament.divisions}
            activeDivisionId={activeDivisionId}
            setActiveDivisionId={setActiveDivisionId}
            addDivision={addDivision}
            removeDivision={removeDivision}
            duplicateDivision={duplicateDivision}
            setActiveTab={setActiveTab}
          />
        );
      case 'division':
        if (!activeDivision) {
          return (
            <div className="bg-surface-container-high p-12 text-center">
              <span className="material-symbols-outlined text-6xl text-on-surface-variant/30 mb-4 block">folder_open</span>
              <h2 className="font-headline text-2xl text-on-surface mb-2 tracking-tighter">NO SECTOR SELECTED</h2>
              <p className="text-on-surface-variant mb-6 text-sm">Select a division from the sidebar or create a new one</p>
              <button onClick={() => setActiveTab('divisions')} className="qw-btn">
                Manage Divisions
              </button>
            </div>
          );
        }
        return (
          <DivisionView
            division={activeDivision}
            updateDivision={(updates) => updateDivision(activeDivision.id, updates)}
            updateAnyDivision={updateDivision}
            tournamentName={tournament.name}
            tournamentMode={tournament.mode}
            tournamentStartDate={tournament.startDate}
            tournamentId={(tournament.name || '')
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/^-|-$/g, '')}
            allDivisions={tournament.divisions}
            tournament={tournament}
            initialSubTab={initialSubTab}
            activeSubTab={activeSubTab}
            setActiveSubTab={setActiveSubTab}
          />
        );
      default:
        return (
          <Dashboard
            tournament={tournament}
            onNavigateToDivision={(divId, subTab) => {
              setActiveDivisionId(divId);
              setInitialSubTab(subTab || 'schedule');
              setActiveTab('division');
            }}
          />
        );
    }
  };

  // ─── Landing screen ──────────────────────────────────────────────
  if (appMode === 'landing') {
    const handleResume = async (draftId) => {
      // Load draft data from Supabase (signed-in) or localStorage (guest)
      let draftData = null;
      if (supabase) {
        const {
          data: { session },
        } = await supabase.auth.getSession();
        if (session) {
          const { data } = await supabase
            .from('tournament_drafts')
            .select('data')
            .eq('id', draftId)
            .single();
          draftData = data?.data ?? null;
        }
      }
      if (!draftData) {
        // Guest fallback
        try {
          const guestDrafts = JSON.parse(localStorage.getItem('qwicky-wizard-drafts') || '[]');
          const found = guestDrafts.find((d) => d.id === draftId);
          draftData = found?.data ?? null;
        } catch {
          draftData = null;
        }
      }
      if (draftData) {
        setTournament((prev) => ({ ...prev, ...draftData }));
      }
      setWizardDraftId(draftId);
      setActiveTab('info');
      setAppMode('wizard');
    };

    return (
      <LandingScreen
        hasExistingData={hasExistingData}
        onCreateNew={() => {
          setTournament(createDefaultTournament());
          setActiveDivisionId(null);
          setActiveTab('info');
          setAppMode('wizard');
        }}
        onLoadFile={(data) => importTournament(data)}
        cloudTournaments={cloudTournaments}
        onLoadFromCloud={async (id) => {
          const loaded = await loadFromCloud(id);
          if (loaded) setAppMode('app');
        }}
        isLoading={isLoading}
        onResume={handleResume}
      />
    );
  }

  // ─── Setup wizard ──────────────────────────────────────────────
  if (appMode === 'wizard') {
    return (
      <SetupWizard
        tournament={tournament}
        updateTournamentInfo={updateTournamentInfo}
        addDivision={addDivisionRaw}
        removeDivision={removeDivision}
        updateDivision={updateDivision}
        onComplete={() => {
          if (tournament.divisions.length > 0) {
            setActiveDivisionId(tournament.divisions[0].id);
            setActiveTab('division');
          }
          setAppMode('app');
        }}
        onSkipToApp={() => setAppMode('app')}
        onBackToLanding={() => setAppMode('landing')}
      />
    );
  }

  // ─── Full app ─────────────────────────────────────────────────
  return (
    <div className="h-screen flex flex-col bg-background">
      <Header
        tournament={tournament}
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        activeDivisionId={activeDivisionId}
        importTournament={importTournament}
        resetTournament={resetTournament}
        onGoHome={() => setAppMode('landing')}
        activeSubTab={activeSubTab}
        setActiveSubTab={setActiveSubTab}
      />

      <div className="flex-1 flex overflow-hidden">
        <Sidebar
          divisions={tournament.divisions}
          activeDivisionId={activeDivisionId}
          onSelectDivision={(divId) => {
            setActiveDivisionId(divId);
            setActiveTab('division');
          }}
          onAddDivision={addDivision}
          activeTab={activeTab}
          setActiveTab={setActiveTab}
        />

        <main className="flex-1 overflow-y-auto bg-surface-dim p-6">
          {renderContent()}
        </main>
      </div>

      <StatusBar />
    </div>
  );
}

export default App;
